In [2]:
# Import libraries
import terality as pd
import numpy as np
import os

You are using version 0.14.14 of the Terality client, but version 0.14.15 is available. Consider upgrading your version to get the latest fixes and features.

In [3]:
path = r'C:\Users\dbnewman18\Instacart_Basket_Analysis_31_03-2022'

In [4]:
df_ords_prods = pd.read_parquet(os.path.join(path, '02 Data', 'Prepared Data', 'orders_products_merged/'))

C:\Users\dbnewman18\Instacart_Basket_Analysis_31_03-2022\02 Data\Prepared Data\
INFO:terality:The result of te.read_parquet was retrieved from cache [docs: https://docs.terality.com/getting-terality/user-guide/caching].

In [5]:
df=df_ords_prods[:1000000]

In [6]:
def price_label(row):

  if row['prices'] <= 5:
    return 'Low-range product'
  elif (row['prices'] > 5) and (row['prices'] <= 15):
    return 'Mid-range product'
  elif row['prices'] > 15:
    return 'High range'
  else: return 'Not enough data'

In [7]:
df['price_range'] = df.apply(price_label, axis=1)

In [8]:
df['price_range'].value_counts(dropna=False)

Mid-range product    634889
Low-range product    331220
Not enough data       24547
High range             9344
Name: price_range, dtype: int64

In [9]:
df['prices'].max()

24.5

In [10]:
df.loc[df['prices'] > 15, 'price_range_loc'] = 'High-range product'

In [11]:
df.loc[(df['prices'] <= 15) & (df['prices'] > 5), 'price_range_loc'] = 'Mid-range product'

In [12]:
df.loc[df['prices'] <= 5, 'price_range_loc'] = 'Low-range product'

In [14]:
for col in df.columns.tolist():
  weird = (df[[col]].applymap(type) != df[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df[weird]) > 0:
    print (col)

WARNING:terality:Slow operation: DataFrame.applymap was executed on our non-parallelized engine [https://www.terality.com/post/inside-terality-the-non-parallelized-engine]. Please reach out to support@terality.com if you’d like us to prioritise the implementation of the function.
WARNING:terality:Slow operation: DataFrame.applymap was executed on our non-parallelized engine [https://www.terality.com/post/inside-terality-the-non-parallelized-engine]. Please reach out to support@terality.com if you’d like us to prioritise the implementation of the function.
WARNING:terality:Slow operation: DataFrame.applymap was executed on our non-parallelized engine [https://www.terality.com/post/inside-terality-the-non-parallelized-engine]. Please reach out to support@terality.com if you’d like us to prioritise the implementation of the function.
WARNING:terality:Slow operation: DataFrame.applymap was executed on our non-parallelized engine [https://www.terality.com/post/inside-terality-the-non-parallelized-engine]. Please reach out to support@terality.com if you’d like us to prioritise the implementation of the function.
WARNING:terality:Slow operation: DataFrame.applymap was executed on our non-parallelized engine [https://www.terality.com/post/inside-terality-the-non-parallelized-engine]. Please reach out to support@terality.com if you’d like us to prioritise the implementation of the function.
WARNING:terality:Slow operation: DataFrame.applymap was executed on our non-parallelized engine [https://www.terality.com/post/inside-terality-the-non-parallelized-engine]. Please reach out to support@terality.com if you’d like us to prioritise the implementation of the function.
WARNING:terality:Slow operation: DataFrame.applymap was executed on our non-parallelized engine [https://www.terality.com/post/inside-terality-the-non-parallelized-engine]. Please reach out to support@terality.com if you’d like us to prioritise the implementation of the function.
WARNING:terality:Slow operation: DataFrame.applymap was executed on our non-parallelized engine [https://www.terality.com/post/inside-terality-the-non-parallelized-engine]. Please reach out to support@terality.com if you’d like us to prioritise the implementation of the function.
WARNING:terality:Slow operation: DataFrame.applymap was executed on our non-parallelized engine [https://www.terality.com/post/inside-terality-the-non-parallelized-engine]. Please reach out to support@terality.com if you’d like us to prioritise the implementation of the function.
WARNING:terality:Slow operation: DataFrame.applymap was executed on our non-parallelized engine [https://www.terality.com/post/inside-terality-the-non-parallelized-engine]. Please reach out to support@terality.com if you’d like us to prioritise the implementation of the function.

product_name

WARNING:terality:Slow operation: DataFrame.applymap was executed on our non-parallelized engine [https://www.terality.com/post/inside-terality-the-non-parallelized-engine]. Please reach out to support@terality.com if you’d like us to prioritise the implementation of the function.
WARNING:terality:Slow operation: DataFrame.applymap was executed on our non-parallelized engine [https://www.terality.com/post/inside-terality-the-non-parallelized-engine]. Please reach out to support@terality.com if you’d like us to prioritise the implementation of the function.
WARNING:terality:Slow operation: DataFrame.applymap was executed on our non-parallelized engine [https://www.terality.com/post/inside-terality-the-non-parallelized-engine]. Please reach out to support@terality.com if you’d like us to prioritise the implementation of the function.
WARNING:terality:Slow operation: DataFrame.applymap was executed on our non-parallelized engine [https://www.terality.com/post/inside-terality-the-non-parallelized-engine]. Please reach out to support@terality.com if you’d like us to prioritise the implementation of the function.
WARNING:terality:Slow operation: DataFrame.applymap was executed on our non-parallelized engine [https://www.terality.com/post/inside-terality-the-non-parallelized-engine]. Please reach out to support@terality.com if you’d like us to prioritise the implementation of the function.
WARNING:terality:Slow operation: DataFrame.applymap was executed on our non-parallelized engine [https://www.terality.com/post/inside-terality-the-non-parallelized-engine]. Please reach out to support@terality.com if you’d like us to prioritise the implementation of the function.

price_range_loc

In [15]:
df['product_name']=df['product_name'].astype('str')

In [16]:
df['price_range_loc']=df['price_range_loc'].astype('str')

In [17]:
df['price_range_loc'].value_counts(dropna=False)

Mid-range product     634889
Low-range product     331220
None                   24547
High-range product      9344
Name: price_range_loc, dtype: int64

In [19]:
result = []

for value in df_ords_prods["prices"]:
  if value <= 5:
    result.append("Low-range product")
  elif value > 5 and value <=15:
    result.append("Mid-range product")
  elif value >15:
    result.append("High-range product")
  else:
    result.append("Not enough data")

WARNING:terality:Iterating data structures is inefficient, see https://docs.terality.com/getting-terality/user-guide/best-practices-and-anti-patterns for more information.

KeyboardInterrupt:

In [30]:
df_ords_prods.loc[df_ords_prods['prices'] > 15, 'price_range'] = 'High-range product'

In [31]:
df_ords_prods.loc[(df_ords_prods['prices'] <= 15) & (df_ords_prods['prices'] > 5), 'price_range'] = 'Mid-range product'

In [32]:
df_ords_prods.loc[df_ords_prods['prices'] <= 5, 'price_range'] = 'Low-range product'

In [34]:
df_ords_prods.drop(['price_range_loc'], axis=1)

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range
0,3139998.0,138.0,28.0,6.0,11.0,3.0,1,5.0,0.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product
1,1977647.0,138.0,30.0,6.0,17.0,20.0,1,1.0,1.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product
2,389851.0,709.0,2.0,0.0,21.0,6.0,1,20.0,0.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product
3,652770.0,764.0,1.0,3.0,13.0,0.0,1,10.0,0.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product
4,1813452.0,764.0,3.0,4.0,17.0,9.0,1,11.0,1.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32435065,1788356.0,200215.0,2.0,0.0,9.0,5.0,49688,27.0,0.0,Fresh Foaming Cleanser,73.0,11.0,13.5,both,Mid-range product
32435066,3401313.0,200377.0,1.0,4.0,11.0,0.0,49688,5.0,0.0,Fresh Foaming Cleanser,73.0,11.0,13.5,both,Mid-range product
32435067,809510.0,200873.0,5.0,3.0,8.0,15.0,49688,12.0,0.0,Fresh Foaming Cleanser,73.0,11.0,13.5,both,Mid-range product
32435068,2359893.0,200873.0,9.0,3.0,15.0,5.0,49688,11.0,1.0,Fresh Foaming Cleanser,73.0,11.0,13.5,both,Mid-range product
32435069,2385091.0,205926.0,11.0,1.0,15.0,6.0,49688,35.0,0.0,Fresh Foaming Cleanser,73.0,11.0,13.5,both,Mid-range product

In [36]:
result = []

for value in df_ords_prods["orders_day_of_week"]:
  if value == 0:
    result.append("Busiest day")
  elif value == 4:
    result.append("Least busy")
  else:
    result.append("Regularly busy")

WARNING:terality:Iterating data structures is inefficient, see https://docs.terality.com/getting-terality/user-guide/best-practices-and-anti-patterns for more information.

In [37]:
df_ords_prods['busiest_day']=result

WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=40, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))': /v1/compute
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=40, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='api.terality2.com', port=443): Read timed out. (read timeout=3)")': /v1/compute
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=40, status=None)) after connection broken by 'ProtocolError('Connection aborted.', timeout('The write operation timed out'))': /v1/compute

SSLError: HTTPSConnectionPool(host='api.terality2.com', port=443): Max retries exceeded with url: /v1/compute (Caused by SSLError(SSLWantWriteError(3, 'The operation did not complete (write) (_ssl.c:2483)')))

# Task 4.7

In [39]:
df_ords_prods.loc[df_ords_prods['orders_day_of_week'] == 0, 'busiest_day'] = 'Busiest day'

In [40]:
df_ords_prods.loc[df_ords_prods['orders_day_of_week'] == 4, 'busiest_day'] = 'Least busy'

In [43]:
df_ords_prods.loc[(df_ords_prods['orders_day_of_week'] != 0) & (df_ords_prods['orders_day_of_week'] != 4), 'busiest_day'] = 'Regularly busy'

In [42]:
df_ords_prods.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range,price_range_loc,busiest_day,busiest day
0,3139998.0,138.0,28.0,6.0,11.0,3.0,1,5.0,0.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product,Mid-range product,None,Regularly busy
1,1977647.0,138.0,30.0,6.0,17.0,20.0,1,1.0,1.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product,Mid-range product,None,Regularly busy
2,389851.0,709.0,2.0,0.0,21.0,6.0,1,20.0,0.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product,Mid-range product,Busiest day,None
3,652770.0,764.0,1.0,3.0,13.0,0.0,1,10.0,0.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product,Mid-range product,None,Regularly busy
4,1813452.0,764.0,3.0,4.0,17.0,9.0,1,11.0,1.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product,Mid-range product,Least busy,None

In [45]:
df_ords_prods.drop(['busiest day'], axis=1)

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range,price_range_loc,busiest_day
0,3139998.0,138.0,28.0,6.0,11.0,3.0,1,5.0,0.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product,Mid-range product,Regularly busy
1,1977647.0,138.0,30.0,6.0,17.0,20.0,1,1.0,1.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product,Mid-range product,Regularly busy
2,389851.0,709.0,2.0,0.0,21.0,6.0,1,20.0,0.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product,Mid-range product,Busiest day
3,652770.0,764.0,1.0,3.0,13.0,0.0,1,10.0,0.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product,Mid-range product,Regularly busy
4,1813452.0,764.0,3.0,4.0,17.0,9.0,1,11.0,1.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product,Mid-range product,Least busy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32435065,1788356.0,200215.0,2.0,0.0,9.0,5.0,49688,27.0,0.0,Fresh Foaming Cleanser,73.0,11.0,13.5,both,Mid-range product,Mid-range product,Busiest day
32435066,3401313.0,200377.0,1.0,4.0,11.0,0.0,49688,5.0,0.0,Fresh Foaming Cleanser,73.0,11.0,13.5,both,Mid-range product,Mid-range product,Least busy
32435067,809510.0,200873.0,5.0,3.0,8.0,15.0,49688,12.0,0.0,Fresh Foaming Cleanser,73.0,11.0,13.5,both,Mid-range product,Mid-range product,Regularly busy
32435068,2359893.0,200873.0,9.0,3.0,15.0,5.0,49688,11.0,1.0,Fresh Foaming Cleanser,73.0,11.0,13.5,both,Mid-range product,Mid-range product,Regularly busy
32435069,2385091.0,205926.0,11.0,1.0,15.0,6.0,49688,35.0,0.0,Fresh Foaming Cleanser,73.0,11.0,13.5,both,Mid-range product,Mid-range product,Regularly busy

In [46]:
df_ords_prods['orders_day_of_week'].value_counts(dropna=False)

0.0    6209808
1.0    5665951
6.0    4500391
2.0    4217868
5.0    4209603
3.0    3844175
4.0    3787263
NaN         11
Name: orders_day_of_week, dtype: int64

In [47]:
df_ords_prods.drop(['busiest_day'], axis=1)

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range,price_range_loc,busiest day
0,3139998.0,138.0,28.0,6.0,11.0,3.0,1,5.0,0.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product,Mid-range product,Regularly busy
1,1977647.0,138.0,30.0,6.0,17.0,20.0,1,1.0,1.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product,Mid-range product,Regularly busy
2,389851.0,709.0,2.0,0.0,21.0,6.0,1,20.0,0.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product,Mid-range product,None
3,652770.0,764.0,1.0,3.0,13.0,0.0,1,10.0,0.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product,Mid-range product,Regularly busy
4,1813452.0,764.0,3.0,4.0,17.0,9.0,1,11.0,1.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product,Mid-range product,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32435065,1788356.0,200215.0,2.0,0.0,9.0,5.0,49688,27.0,0.0,Fresh Foaming Cleanser,73.0,11.0,13.5,both,Mid-range product,Mid-range product,None
32435066,3401313.0,200377.0,1.0,4.0,11.0,0.0,49688,5.0,0.0,Fresh Foaming Cleanser,73.0,11.0,13.5,both,Mid-range product,Mid-range product,None
32435067,809510.0,200873.0,5.0,3.0,8.0,15.0,49688,12.0,0.0,Fresh Foaming Cleanser,73.0,11.0,13.5,both,Mid-range product,Mid-range product,Regularly busy
32435068,2359893.0,200873.0,9.0,3.0,15.0,5.0,49688,11.0,1.0,Fresh Foaming Cleanser,73.0,11.0,13.5,both,Mid-range product,Mid-range product,Regularly busy
32435069,2385091.0,205926.0,11.0,1.0,15.0,6.0,49688,35.0,0.0,Fresh Foaming Cleanser,73.0,11.0,13.5,both,Mid-range product,Mid-range product,Regularly busy

### Creating Busiest/Slowest Column

In [64]:
df_ords_prods.loc[df_ords_prods['orders_day_of_week'] <= 1, 'busiest_slowest'] = 'Busiest'

In [65]:
df_ords_prods.loc[(df_ords_prods['orders_day_of_week'] >= 3) & (df_ords_prods['orders_day_of_week'] < 5), 'busiest_slowest'] = 'Slowest'

In [57]:
df_ords_prods.loc[(df_ords_prods['orders_day_of_week'] != 0) & (df_ords_prods['orders_day_of_week'] != 1) & (df_ords_prods['orders_day_of_week'] != 3) & (df_ords_prods['orders_day_of_week'] != 4), 'busiest_slowest'] = 'Regular'

In [67]:
df_ords_prods.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range,price_range_loc,busiest_slowest
0,3139998.0,138.0,28.0,6.0,11.0,3.0,1,5.0,0.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product,Mid-range product,Regular
1,1977647.0,138.0,30.0,6.0,17.0,20.0,1,1.0,1.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product,Mid-range product,Regular
2,389851.0,709.0,2.0,0.0,21.0,6.0,1,20.0,0.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product,Mid-range product,Busiest
3,652770.0,764.0,1.0,3.0,13.0,0.0,1,10.0,0.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product,Mid-range product,Slowest
4,1813452.0,764.0,3.0,4.0,17.0,9.0,1,11.0,1.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product,Mid-range product,Slowest

In [68]:
df_ords_prods.drop(['price_range_loc'], axis=1, inplace=True)

In [69]:
df_ords_prods.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range,busiest_slowest
0,3139998.0,138.0,28.0,6.0,11.0,3.0,1,5.0,0.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product,Regular
1,1977647.0,138.0,30.0,6.0,17.0,20.0,1,1.0,1.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product,Regular
2,389851.0,709.0,2.0,0.0,21.0,6.0,1,20.0,0.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product,Busiest
3,652770.0,764.0,1.0,3.0,13.0,0.0,1,10.0,0.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product,Slowest
4,1813452.0,764.0,3.0,4.0,17.0,9.0,1,11.0,1.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product,Slowest

In [70]:
df_ords_prods['busiest_slowest'].value_counts(dropna=False)

Regular    12927873
Busiest    11875759
Slowest     7631438
Name: busiest_slowest, dtype: int64

The number of orders on "regular" days (Monday, Thurs, Friday) actually outnumbers the number of orders on the two busiest days (Saturday and Sunday).

In [71]:
df_ords_prods['order_hour_of_day'].value_counts(dropna=False)

10.0    2764476
11.0    2738647
14.0    2691598
15.0    2664583
13.0    2663346
12.0    2620898
16.0    2537506
9.0     2456751
17.0    2089510
8.0     1719991
18.0    1637956
19.0    1259416
20.0     977049
7.0      891951
21.0     796379
22.0     634743
23.0     402621
6.0      290796
0.0      218951
1.0      115787
5.0       88064
2.0       69435
4.0       53284
3.0       51321
NaN          11
Name: order_hour_of_day, dtype: int64

In [72]:
df_ords_prods['order_hour_of_day'].describe()

count    3.243506e+07
mean     1.342498e+01
std      4.246357e+00
min      0.000000e+00
25%      1.000000e+01
50%      1.300000e+01
75%      1.600000e+01
max      2.300000e+01
Name: order_hour_of_day, dtype: float64

In [87]:
df_ords_prods.loc[df_ords_prods['order_hour_of_day'] < 7, 'busy_hours'] = 'Fewest orders'

In [74]:
df_ords_prods.loc[df_ords_prods['order_hour_of_day'] == 23, 'busy_hours'] = 'Fewest orders'

In [76]:
df_ords_prods.loc[(df_ords_prods['order_hour_of_day'] >= 17) & (df_ords_prods['order_hour_of_day'] <= 22), 'busy_hours'] = 'Average orders'

In [77]:
df_ords_prods.loc[(df_ords_prods['order_hour_of_day'] >= 7) & (df_ords_prods['order_hour_of_day'] < 9), 'busy_hours'] = 'Average orders'

In [78]:
df_ords_prods.loc[(df_ords_prods['order_hour_of_day'] >= 9) & (df_ords_prods['order_hour_of_day'] < 17), 'busy_hours'] = 'Most orders'

In [79]:
df_ords_prods['busy_hours'].value_counts(dropna=False)

Most orders       21137805
Average orders    10006995
NaN                 887649
Fewest orders       402621
Name: busy_hours, dtype: int64

In [80]:
df_ords_prods.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range,busiest_slowest,busiest_hours,busy_hours
0,3139998.0,138.0,28.0,6.0,11.0,3.0,1,5.0,0.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product,Regular,None,Most orders
1,1977647.0,138.0,30.0,6.0,17.0,20.0,1,1.0,1.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product,Regular,None,Average orders
2,389851.0,709.0,2.0,0.0,21.0,6.0,1,20.0,0.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product,Busiest,None,Average orders
3,652770.0,764.0,1.0,3.0,13.0,0.0,1,10.0,0.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product,Slowest,None,Most orders
4,1813452.0,764.0,3.0,4.0,17.0,9.0,1,11.0,1.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product,Slowest,None,Average orders

In [82]:
df_nan=df_ords_prods[df_ords_prods['busy_hours'].isnull()==True]

In [83]:
df_nan.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range,busiest_slowest,busiest_hours,busy_hours
17,200390.0,1540.0,4.0,2.0,0.0,7.0,1,10.0,0.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product,Regular,Fewest orders,None
19,2920553.0,1540.0,6.0,1.0,0.0,14.0,1,9.0,1.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product,Busiest,Fewest orders,None
20,2813049.0,1540.0,7.0,2.0,2.0,8.0,1,7.0,1.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product,Regular,Fewest orders,None
22,1604797.0,1540.0,9.0,1.0,3.0,28.0,1,6.0,1.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product,Busiest,Fewest orders,None
32,1424793.0,1540.0,27.0,1.0,1.0,5.0,1,1.0,1.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product,Busiest,Fewest orders,None

In [84]:
df_ords_prods.drop(['busiest_hours'], axis=1)

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range,busiest_slowest,busy_hours
0,3139998.0,138.0,28.0,6.0,11.0,3.0,1,5.0,0.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product,Regular,Most orders
1,1977647.0,138.0,30.0,6.0,17.0,20.0,1,1.0,1.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product,Regular,Average orders
2,389851.0,709.0,2.0,0.0,21.0,6.0,1,20.0,0.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product,Busiest,Average orders
3,652770.0,764.0,1.0,3.0,13.0,0.0,1,10.0,0.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product,Slowest,Most orders
4,1813452.0,764.0,3.0,4.0,17.0,9.0,1,11.0,1.0,Chocolate Sandwich Cookies,61.0,19.0,5.8,both,Mid-range product,Slowest,Average orders
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32435065,1788356.0,200215.0,2.0,0.0,9.0,5.0,49688,27.0,0.0,Fresh Foaming Cleanser,73.0,11.0,13.5,both,Mid-range product,Busiest,Most orders
32435066,3401313.0,200377.0,1.0,4.0,11.0,0.0,49688,5.0,0.0,Fresh Foaming Cleanser,73.0,11.0,13.5,both,Mid-range product,Slowest,Most orders
32435067,809510.0,200873.0,5.0,3.0,8.0,15.0,49688,12.0,0.0,Fresh Foaming Cleanser,73.0,11.0,13.5,both,Mid-range product,Slowest,Average orders
32435068,2359893.0,200873.0,9.0,3.0,15.0,5.0,49688,11.0,1.0,Fresh Foaming Cleanser,73.0,11.0,13.5,both,Mid-range product,Slowest,Most orders
32435069,2385091.0,205926.0,11.0,1.0,15.0,6.0,49688,35.0,0.0,Fresh Foaming Cleanser,73.0,11.0,13.5,both,Mid-range product,Busiest,Most orders

In [86]:
df_nan['order_hour_of_day'].value_counts(dropna=False)

6.0    290796
0.0    218951
1.0    115787
5.0     88064
2.0     69435
4.0     53284
3.0     51321
NaN        11
Name: order_hour_of_day, dtype: int64

In [90]:
df_ords_prods['busy_hours'] = df_ords_prods['busy_hours'].astype('str')

In [91]:
df_ords_prods['busy_hours'].value_counts(dropna=False)

Most orders       21137805
Average orders    10006995
Fewest orders      1290259
None                    11
Name: busy_hours, dtype: int64

In [92]:
df_ords_prods.to_parquet_folder(os.path.join(path, '02 Data','Prepared Data', 'orders_products_cols_added*.parquet'))